name: Test
run-name: Test end-to-end
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        browser:
          - electron
          - chrome
          - firefox
          - webkit
        include:
          - os: ubuntu-latest
            name: Linux
          - os: macos-latest
            name: macOS
          - os: windows-latest
            name: Windows
          - os: windows-latest
            name: Windows
            browser: edge
        exclude:
          - os: windows-latest
            browser: webkit

    name: ${{ matrix.name }} - ${{ matrix.browser }}
    runs-on: ${{ matrix.os }}
    # add exceptions for failing jobs here
    continue-on-error: false
    steps:
      - name: Setup firefox (macOS)
        if: matrix.os == 'macos-latest' && matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@v1
      - name: Setup webkit (Linux)
        if: matrix.os == 'ubuntu-latest' && matrix.browser == 'webkit'
        run: npx playwright install-deps webkit
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: leanprover/lean-action@v1
        if: matrix.os != 'windows-latest'
        with:
          lake-package-directory: "demo/server/LeanProject"
          use-github-cache: false
          use-mathlib-cache: false
          auto-config: false
          build: false
          test: false
          lint: false
      - name: Install elan (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf > elan-init.sh
          bash elan-init.sh -y
          echo "$(realpath ~/.elan/bin)" >> $GITHUB_PATH
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run setup_demo
      - name: Run tests
        if: matrix.os != 'windows-latest'
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:5173'
          browser: ${{ matrix.browser }}
      - name: Run tests (Windows)
        run: |
          npx concurrently --hide 0 --kill-others \
            "npm start" \
            "npx wait-on http://localhost:5173 && \
            cypress run --browser ${{ matrix.browser }}" -n server,cypress -s command-cypress
        if: matrix.os == 'windows-latest'
